# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[
  {
    goPackagePath = "github.com/google/uuid";
    fetch = {
      type = "git";
      url = "https://github.com/google/uuid";
      rev = "9b3b1e0f5f99ae461456d768e7d301a7acdaa2d8";
      sha256 = "0yx4kiafyshdshrmrqcf2say5mzsviz7r94a0y1l6xfbkkyvnc86";
    };
  }
]
